version: '3.8'

services:
  rabbitmq:
    container_name: queue
    build:
      context: ./rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - queue-data:/var/lib/rabbitmq

volumes:
  queue-data: