spring:
  application:
    name: pubsub-producer
  rabbitmq:
    host: localhost
    port: 5672
    username: app-user
    password: admin
    virtual-host: my-vhost

rabbitmq:
  charge:
    exchange: exchange.topic
    routing_key: charge.*