spring:
  application:
    name: pubsub-producer
  rabbitmq:
    host: localhost
    port: 5672
    username: app-user
    password: admin
    virtual-host: my-vhost

rabbitmq:
  charge:
    exchange: exchange
    routing_key: charge.create
  point:
    exchange: exchange
    routing_key: charge.point
  mail:
    exchange: exchange
    routing_key: charge.mail