spring:
  application:
    name: pubsub-sandbox
  rabbitmq:
    host: localhost
    port: 5672
    username: app-user
    password: admin
    virtual-host: my-vhost

rabbitmq:
  charge:
    queue-name: charge 

server:
  port: 8081